sudo: require
dist: trusty #precise #xenial
language: python

matrix:
  include:
    - python: 3.6

cache:
  apt: true
  directories:
    - $HOME/.local

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - texlive-base
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra

script:
  #- bash test.sh ./ main
   - export PYTHONPATH=$PYTHONPATH:.
   - nosetests -v
